on:
  push:
    branches:
      - 'master'
    paths:
      - 'manylinux_2_28/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'manylinux_2_28/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ x86_64, aarch64 ]
    name: Build & deploy ``manylinux_2_28`` image for arch ``${{ matrix.arch }}``
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Determine tag
        id: tag
        run: echo ::set-output name=tag::$(git log -n1 --pretty="format:%cs-%h" ${{ github.sha }})
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: manylinux_2_28/${{ matrix.arch }}
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          tags: |
            eoshep/manylinux_2_28:latest
            eoshep/manylinux_2_28:${{ steps.tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
